# Generated by Django 6.0.3 on 2026-03-19 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['created_at'], 'verbose_name': 'Poll', 'verbose_name_plural': 'Polls'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_multiple',
        ),
        migrations.AlterField(
            model_name='question',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordering'),
        ),
        migrations.CreateModel(
            name='PollSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='polls.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Poll Session',
                'verbose_name_plural': 'Poll Sessions',
                'unique_together': {('user', 'poll')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='polls.pollsession'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together={('session', 'question')},
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
    ]
