# Generated by Django 6.0.3 on 2026-03-19 21:37

import polls.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_poll_options_remove_question_is_multiple_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollsession',
            name='slug',
            field=models.SlugField(default=polls.helpers.get_random_slug, max_length=32, unique=True),
        ),
    ]
